### ISSUE TITLE
Cannot View Estimates and Invoice PDF

### ISSUE THREAD

**Issue by goldcoders** [bytefury/crater#145]
I tried creating a new Estimates Save it Successfully
But when i Try to View it im getting 500 error

here is the stacktrace
```
[2020-01-24 07:11:51] local.ERROR: Invalid characters passed for attempted conversion, these have been ignored {"exception":"[object] (ErrorException(code: 0): Invalid characters passed for attempted conversion, these have been ignored at /home/uriah/www/crater/vendor/dompdf/dompdf/lib/Cpdf.php:2598)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /home/uriah/www/crater/vendor/dompdf/dompdf/lib/Cpdf.php(2598): hexdec()
#2 /home/uriah/www/crater/vendor/dompdf/dompdf/lib/Cpdf.php(2669): Cpdf->openFont()
#3 /home/uriah/www/crater/vendor/dompdf/dompdf/src/Adapter/CPDF.php(1006): Cpdf->selectFont()
#4 /home/uriah/www/crater/vendor/dompdf/dompdf/src/FontMetrics.php(310): Dompdf\\Adapter\\CPDF->get_font_height()
#5 /home/uriah/www/crater/vendor/dompdf/dompdf/src/FrameReflower/Text.php(197): Dompdf\\FontMetrics->getFontHeight()
#6 /home/uriah/www/crater/vendor/dompdf/dompdf/src/FrameReflower/Text.php(372): Dompdf\\FrameReflower\\Text->_layout_line()
#7 /home/uriah/www/crater/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(895): Dompdf\\FrameReflower\\Text->reflow()
#8 /home/uriah/www/crater/vendor/dompdf/dompdf/src/FrameReflower/Block.php(845): Dompdf\\FrameDecorator\\AbstractFrameDecorator->reflow()
#9 /home/uriah/www/crater/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(895): Dompdf\\FrameReflower\\Block->reflow()
#10 /home/uriah/www/crater/vendor/dompdf/dompdf/src/FrameReflower/Page.php(141): Dompdf\\FrameDecorator\\AbstractFrameDecorator->reflow()
#11 /home/uriah/www/crater/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(895): Dompdf\\FrameReflower\\Page->reflow()
#12 /home/uriah/www/crater/vendor/dompdf/dompdf/src/Dompdf.php(847): Dompdf\\FrameDecorator\\AbstractFrameDecorator->reflow()
#13 /home/uriah/www/crater/vendor/barryvdh/laravel-dompdf/src/PDF.php(195): Dompdf\\Dompdf->render()
#14 /home/uriah/www/crater/vendor/barryvdh/laravel-dompdf/src/PDF.php(142): Barryvdh\\DomPDF\\PDF->render()
#15 /home/uriah/www/crater/vendor/barryvdh/laravel-dompdf/src/PDF.php(180): Barryvdh\\DomPDF\\PDF->output()
#16 /home/uriah/www/crater/app/Http/Controllers/FrontendController.php(378): Barryvdh\\DomPDF\\PDF->stream()
#17 [internal function]: Crater\\Http\\Controllers\\FrontendController->getInvoicePdf()
#18 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#19 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#20 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#21 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#22 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
#23 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#24 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#26 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#28 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#30 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle()
#32 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#34 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#36 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then()
#38 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack()
#39 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute()
#40 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute()
#41 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch()
#42 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#43 /home/uriah/www/crater/app/Http/Middleware/ConfigMiddleware.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Crater\\Http\\Middleware\\ConfigMiddleware->handle()
#45 /home/uriah/www/crater/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle()
#47 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#49 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#51 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#53 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#55 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then()
#57 /home/uriah/www/crater/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#58 /home/uriah/www/crater/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
#59 /home/uriah/.config/composer/vendor/cpriego/valet-linux/server.php(232): require('/home/uriah/www...')
#60 {main}
"} 
```

**Comment by goldcoders** [comment]
yes this error occurs on php 7.4 , im using archlinux and im using all bleading edge technology,
so for users like me who like to live on the edge...

the solution here  temporarily is update this on your vendors folder.
vendor/dompdf/dompdf/lib/Cpdf.php
line : 2598
```
if (ctype_xdigit($c) && ctype_xdigit($n)) {
                                    $data['codeToName'][$c] = $n;
                                }
```

**Comment by goldcoders** [comment]
im not planning to used this on production just on my local computer so editing that file is quick fix for me

**Comment by mdpoulter** [comment]
It seems that this error is fixed by updating [dompdf/dompdf](https://github.com/dompdf/dompdf) to v0.8.4, however then the PDF rendering itself has some weird formatting issues with the new version.

**Comment by mohitpanjwani** [comment]
Fixed the issue on latest update: https://github.com/bytefury/crater/releases/tag/3.1.1
